version : '3.1'

services : 
        
        database:
                build: ./persistence/
                ports:
                        - 3306:3306
                environment:
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_DATABASE: computer-database-db
        webserver:
                build: ./webapp/
                ports:
                        - 8080:8080
                links:
                        - database
